# The title of the website, if left empty this will default to the repository name
title: Blog for Public Code

# Jekyll plugins that are supported by GitHub pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from

# Also render the README to HTML even if there is an index.md
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - README.md

# Exclude the `vendor` folder created by Travis
exclude:
  - vendor

# Use the Foundation For Public Code Jekyll theme
remote_theme: publiccodenet/jekyll-theme

# Enable a feed link for the blog
feed_link: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
